[build]
  command = "node build.js"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/image/*"
  to = "/.netlify/functions/image/:splat"
  status = 200
  
  [[plugins]]
  package = "@netlify/plugin-functions-install-core"
